version: '3.9'
services:
  dev:
    tty: true
    build: 
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    volumes:
      - ../:/work
    tmpfs: /work/target:uid=1000,gid=1000,exec
